#include "toolchain/runtime_library.h"

// The runtime source is C++ in the compiler's own supported subset.
// Layout contracts (all fixed by the Itanium ABI or by this
// implementation's backend):
//
// - Exception records: {dtor, type_info, next_caught, handler_count,
//   rethrown, slot, pad}, payload at +64, allocated from a static
//   slot arena (no host allocator exists at this stage).
// - RTTI records: the first word points 16 bytes past one of the
//   __cxxabiv1 vtable anchor objects defined here; the anchor address
//   classifies the record kind. Class records are {vptr, name},
//   single-inheritance adds the base record, vmi adds
//   {u32 flags, u32 count, {base, i64 offset_flags}...} where
//   offset_flags is (offset << 8 | flags) and flag bit 2 marks a
//   public base.
// - Vtables: the address point is preceded by offset-to-top (-16)
//   and the RTTI pointer (-8), which __dynamic_cast reads.
// - The linker's support module owns __cppgm_eh_top /
//   __cppgm_eh_selector / __cppgm_eh_exception and the
//   __cppgm_unwind_raise / __cppgm_exit primitives.

namespace toolchain {

namespace {

const char * const kRuntimeLines[] = {
	"typedef unsigned long cppgm_usize;",
	"typedef void (*cppgm_dtor)(void *);",
	"",
	"extern \"C\" { extern void * __cppgm_eh_top; }",
	"extern \"C\" { extern long __cppgm_eh_selector; }",
	"extern \"C\" { extern void * __cppgm_eh_exception; }",
	"extern \"C\" void __cppgm_unwind_raise();",
	"extern \"C\" void __cppgm_exit(long status);",
	"",
	"extern \"C\" unsigned long",
	"    _ZTVN10__cxxabiv117__class_type_infoE[8] = {0};",
	"extern \"C\" unsigned long",
	"    _ZTVN10__cxxabiv120__si_class_type_infoE[8] = {0};",
	"extern \"C\" unsigned long",
	"    _ZTVN10__cxxabiv121__vmi_class_type_infoE[8] = {0};",
	"extern \"C\" unsigned long",
	"    _ZTVN10__cxxabiv119__pointer_type_infoE[8] = {0};",
	"extern \"C\" unsigned long",
	"    _ZTVN10__cxxabiv123__fundamental_type_infoE[8] = {0};",
	"",
	"namespace {",
	"",
	"struct CppgmEhRecord",
	"{",
	"  cppgm_dtor dtor;",
	"  void * tinfo;",
	"  CppgmEhRecord * next_caught;",
	"  long handler_count;",
	"  long rethrown;",
	"  long slot;",
	"  void * adjusted;",
	"  long pad;",
	"};",
	"",
	"enum { CPPGM_EH_SLOTS = 16, CPPGM_EH_SLOT_WORDS = 512 };",
	"",
	"unsigned long cppgm_eh_arena[CPPGM_EH_SLOTS][CPPGM_EH_SLOT_WORDS];",
	"long cppgm_eh_arena_used[CPPGM_EH_SLOTS];",
	"CppgmEhRecord * cppgm_eh_caught_top;",
	"",
	"char * cppgm_eh_payload(CppgmEhRecord * record)",
	"{",
	"  return (char *)record + sizeof(CppgmEhRecord);",
	"}",
	"",
	"void * cppgm_anchor_point(unsigned long * anchor)",
	"{",
	"  return (char *)anchor + 16;",
	"}",
	"",
	"// The record-kind anchors: a type_info record's first word.",
	"void * cppgm_record_kind(void * record)",
	"{",
	"  return *(void **)record;",
	"}",
	"",
	"bool cppgm_is_class_kind(void * kind)",
	"{",
	"  return kind == cppgm_anchor_point(_ZTVN10__cxxabiv117__class_type_infoE)",
	"      || kind == cppgm_anchor_point(_ZTVN10__cxxabiv120__si_class_type_infoE)",
	"      || kind == cppgm_anchor_point(_ZTVN10__cxxabiv121__vmi_class_type_infoE);",
	"}",
	"",
	"// Walks `record`'s class hierarchy looking for `target` reachable",
	"// through public paths, accumulating the subobject offset.",
	"bool cppgm_find_public_base(void * record, void * target,",
	"                            long offset, long * found_offset)",
	"{",
	"  if (record == target)",
	"  {",
	"    *found_offset = offset;",
	"    return true;",
	"  }",
	"  void * kind = cppgm_record_kind(record);",
	"  if (kind ==",
	"      cppgm_anchor_point(_ZTVN10__cxxabiv120__si_class_type_infoE))",
	"  {",
	"    void * base = *(void **)((char *)record + 16);",
	"    return cppgm_find_public_base(base, target, offset, found_offset);",
	"  }",
	"  if (kind ==",
	"      cppgm_anchor_point(_ZTVN10__cxxabiv121__vmi_class_type_infoE))",
	"  {",
	"    unsigned int count = *(unsigned int *)((char *)record + 20);",
	"    for (unsigned int i = 0; i < count; i++)",
	"    {",
	"      char * entry = (char *)record + 24 + 16 * (long)i;",
	"      void * base = *(void **)entry;",
	"      long offset_flags = *(long *)(entry + 8);",
	"      if ((offset_flags & 2) == 0)",
	"        continue;",
	"      if (cppgm_find_public_base(base, target,",
	"                                 offset + (offset_flags >> 8),",
	"                                 found_offset))",
	"        return true;",
	"    }",
	"  }",
	"  return false;",
	"}",
	"",
	"// 15.3: does a handler of type `catch_ti` match an exception whose",
	"// static type record is `thrown_ti`? On success `*adjusted` is the",
	"// object pointer the handler receives.",
	"bool cppgm_eh_type_matches(void * catch_ti, void * thrown_ti,",
	"                           char * payload, void ** adjusted)",
	"{",
	"  if (catch_ti == thrown_ti)",
	"  {",
	"    *adjusted = payload;",
	"    return true;",
	"  }",
	"  if (cppgm_is_class_kind(cppgm_record_kind(thrown_ti)) &&",
	"      cppgm_is_class_kind(cppgm_record_kind(catch_ti)))",
	"  {",
	"    long offset = 0;",
	"    if (cppgm_find_public_base(thrown_ti, catch_ti, 0, &offset))",
	"    {",
	"      *adjusted = payload + offset;",
	"      return true;",
	"    }",
	"    return false;",
	"  }",
	"  if (cppgm_record_kind(thrown_ti) ==",
	"          cppgm_anchor_point(_ZTVN10__cxxabiv119__pointer_type_infoE) &&",
	"      cppgm_record_kind(catch_ti) ==",
	"          cppgm_anchor_point(_ZTVN10__cxxabiv119__pointer_type_infoE))",
	"  {",
	"    void * thrown_pointee = *(void **)((char *)thrown_ti + 24);",
	"    void * catch_pointee = *(void **)((char *)catch_ti + 24);",
	"    if (thrown_pointee == catch_pointee)",
	"    {",
	"      *adjusted = payload;",
	"      return true;",
	"    }",
	"    long offset = 0;",
	"    if (cppgm_is_class_kind(cppgm_record_kind(thrown_pointee)) &&",
	"        cppgm_is_class_kind(cppgm_record_kind(catch_pointee)) &&",
	"        cppgm_find_public_base(thrown_pointee, catch_pointee, 0,",
	"                               &offset))",
	"    {",
	"      *(char **)payload += offset;",
	"      *adjusted = payload;",
	"      return true;",
	"    }",
	"  }",
	"  return false;",
	"}",
	"",
	"}  // namespace",
	"",
	"extern \"C\" void * __cxa_allocate_exception(cppgm_usize size)",
	"{",
	"  cppgm_usize need = size + sizeof(CppgmEhRecord);",
	"  if (need > sizeof(cppgm_eh_arena[0]))",
	"    __cppgm_exit(134);",
	"  for (long i = 0; i < CPPGM_EH_SLOTS; i++)",
	"  {",
	"    if (cppgm_eh_arena_used[i])",
	"      continue;",
	"    cppgm_eh_arena_used[i] = 1;",
	"    CppgmEhRecord * record = (CppgmEhRecord *)cppgm_eh_arena[i];",
	"    record->dtor = 0;",
	"    record->tinfo = 0;",
	"    record->next_caught = 0;",
	"    record->handler_count = 0;",
	"    record->rethrown = 0;",
	"    record->slot = i;",
	"    record->adjusted = 0;",
	"    return cppgm_eh_payload(record);",
	"  }",
	"  __cppgm_exit(134);",
	"  return 0;",
	"}",
	"",
	"extern \"C\" void __cxa_free_exception(void * payload)",
	"{",
	"  CppgmEhRecord * record =",
	"      (CppgmEhRecord *)((char *)payload - sizeof(CppgmEhRecord));",
	"  cppgm_eh_arena_used[record->slot] = 0;",
	"}",
	"",
	"extern \"C\" void __cxa_throw(void * payload, void * tinfo,",
	"                             cppgm_dtor dtor)",
	"{",
	"  CppgmEhRecord * record =",
	"      (CppgmEhRecord *)((char *)payload - sizeof(CppgmEhRecord));",
	"  record->tinfo = tinfo;",
	"  record->dtor = dtor;",
	"  record->adjusted = payload;",
	"  __cppgm_eh_exception = record;",
	"  __cppgm_unwind_raise();",
	"}",
	"",
	"// Handler-classification markers call this in dispatch order; the",
	"// first match claims the selector and the adjusted object pointer.",
	"extern \"C\" void __cppgm_eh_match(void * catch_ti, long selector)",
	"{",
	"  if (__cppgm_eh_selector != 0)",
	"    return;",
	"  CppgmEhRecord * record = (CppgmEhRecord *)__cppgm_eh_exception;",
	"  if (record == 0)",
	"    return;",
	"  void * adjusted = cppgm_eh_payload(record);",
	"  if (catch_ti != 0 &&",
	"      !cppgm_eh_type_matches(catch_ti, record->tinfo,",
	"                             cppgm_eh_payload(record), &adjusted))",
	"    return;",
	"  record->adjusted = adjusted;",
	"  __cppgm_eh_selector = selector;",
	"}",
	"",
	"extern \"C\" void * __cxa_begin_catch(void * cookie)",
	"{",
	"  CppgmEhRecord * record = (CppgmEhRecord *)cookie;",
	"  record->handler_count = record->handler_count + 1;",
	"  if (record != cppgm_eh_caught_top)",
	"  {",
	"    record->next_caught = cppgm_eh_caught_top;",
	"    cppgm_eh_caught_top = record;",
	"  }",
	"  return record->adjusted;",
	"}",
	"",
	"extern \"C\" void __cxa_end_catch()",
	"{",
	"  CppgmEhRecord * record = cppgm_eh_caught_top;",
	"  if (record == 0)",
	"    __cppgm_exit(134);",
	"  record->handler_count = record->handler_count - 1;",
	"  if (record->handler_count > 0)",
	"    return;",
	"  cppgm_eh_caught_top = record->next_caught;",
	"  if (record->rethrown)",
	"  {",
	"    record->rethrown = 0;",
	"    return;",
	"  }",
	"  if (record->dtor)",
	"    record->dtor(cppgm_eh_payload(record));",
	"  cppgm_eh_arena_used[record->slot] = 0;",
	"}",
	"",
	"extern \"C\" void __cxa_rethrow()",
	"{",
	"  CppgmEhRecord * record = cppgm_eh_caught_top;",
	"  if (record == 0)",
	"    __cppgm_exit(134);",
	"  record->rethrown = 1;",
	"  __cppgm_eh_exception = record;",
	"  __cppgm_unwind_raise();",
	"}",
	"",
	"extern \"C\" void _Unwind_Resume(void *)",
	"{",
	"  __cppgm_unwind_raise();",
	"}",
	"",
	"extern \"C\" void __gxx_personality_v0()",
	"{",
	"}",
	"",
	"// __dynamic_cast helpers: subobject searches over the RTTI graph.",
	"namespace {",
	"",
	"struct CppgmCastSearch",
	"{",
	"  void * dst_ti;",
	"  void * src_ti;",
	"  char * src_address;",
	"  char * result;",
	"  long result_count;",
	"  long src_public_in_whole;",
	"};",
	"",
	"// Enumerates every subobject; records public dst subobjects and",
	"// whether the src subobject sits on a public path from the root.",
	"void cppgm_cast_walk(CppgmCastSearch * search, void * record,",
	"                     char * address, bool is_public)",
	"{",
	"  if (record == search->src_ti && address == search->src_address &&",
	"      is_public)",
	"    search->src_public_in_whole = 1;",
	"  if (record == search->dst_ti && is_public)",
	"  {",
	"    long offset = 0;",
	"    if (cppgm_find_public_base(record, search->src_ti, 0, &offset) &&",
	"        address + offset == search->src_address)",
	"    {",
	"      if (search->result != address)",
	"      {",
	"        search->result_count = search->result_count + 1;",
	"        search->result = address;",
	"      }",
	"      return;",
	"    }",
	"  }",
	"  void * kind = cppgm_record_kind(record);",
	"  if (kind ==",
	"      cppgm_anchor_point(_ZTVN10__cxxabiv120__si_class_type_infoE))",
	"  {",
	"    void * base = *(void **)((char *)record + 16);",
	"    cppgm_cast_walk(search, base, address, is_public);",
	"    return;",
	"  }",
	"  if (kind ==",
	"      cppgm_anchor_point(_ZTVN10__cxxabiv121__vmi_class_type_infoE))",
	"  {",
	"    unsigned int count = *(unsigned int *)((char *)record + 20);",
	"    for (unsigned int i = 0; i < count; i++)",
	"    {",
	"      char * entry = (char *)record + 24 + 16 * (long)i;",
	"      void * base = *(void **)entry;",
	"      long offset_flags = *(long *)(entry + 8);",
	"      bool base_public = (offset_flags & 2) != 0;",
	"      cppgm_cast_walk(search, base, address + (offset_flags >> 8),",
	"                      is_public && base_public);",
	"    }",
	"  }",
	"}",
	"",
	"}  // namespace",
	"",
	"extern \"C\" void * __dynamic_cast(void * sub, void * src_ti,",
	"                                  void * dst_ti, long src2dst)",
	"{",
	"  if (sub == 0)",
	"    return 0;",
	"  char * vptr = *(char **)sub;",
	"  long offset_to_top = *(long *)(vptr - 16);",
	"  void * whole_ti = *(void **)(vptr - 8);",
	"  char * whole = (char *)sub + offset_to_top;",
	"  CppgmCastSearch search;",
	"  search.dst_ti = dst_ti;",
	"  search.src_ti = src_ti;",
	"  search.src_address = (char *)sub;",
	"  search.result = 0;",
	"  search.result_count = 0;",
	"  search.src_public_in_whole = 0;",
	"  cppgm_cast_walk(&search, whole_ti, whole, true);",
	"  if (search.result_count == 1)",
	"    return search.result;",
	"  // Cross cast: a unique public dst subobject when the source",
	"  // subobject itself is public in the complete object.",
	"  if (search.src_public_in_whole == 0)",
	"    return 0;",
	"  long dst_count = 0;",
	"  char * dst_address = 0;",
	"  long dst_offset = 0;",
	"  if (whole_ti == dst_ti)",
	"  {",
	"    dst_count = 1;",
	"    dst_address = whole;",
	"  }",
	"  else if (cppgm_find_public_base(whole_ti, dst_ti, 0, &dst_offset))",
	"  {",
	"    dst_count = 1;",
	"    dst_address = whole + dst_offset;",
	"  }",
	"  return dst_count == 1 ? dst_address : 0;",
	"}",
	"",
	"extern \"C\" void __cxa_bad_cast()",
	"{",
	"  __cppgm_exit(134);",
	"}",
	"",
	"extern \"C\" void __cxa_bad_typeid()",
	"{",
	"  __cppgm_exit(134);",
	"}",
	"",
	"extern \"C\" int __cxa_pure_virtual(void *)",
	"{",
	"  __cppgm_exit(134);",
	"  return 0;",
	"}",
	"",
	"namespace {",
	"",
	"enum { CPPGM_HEAP_WORDS = 1 << 18 };",
	"",
	"unsigned long cppgm_heap[CPPGM_HEAP_WORDS];",
	"cppgm_usize cppgm_heap_next;",
	"",
	"}  // namespace",
	"",
	"extern \"C\" void * cppgm_builtin_operator_new(cppgm_usize size)",
	"{",
	"  cppgm_usize words = (size + 15) / 8 & ~(cppgm_usize)1;",
	"  if (words == 0)",
	"    words = 2;",
	"  if (cppgm_heap_next + words > (cppgm_usize)CPPGM_HEAP_WORDS)",
	"    __cppgm_exit(134);",
	"  void * result = &cppgm_heap[cppgm_heap_next];",
	"  cppgm_heap_next = cppgm_heap_next + words;",
	"  return result;",
	"}",
	"",
	"extern \"C\" void cppgm_builtin_operator_delete(void *)",
	"{",
	"}",
};

}  // namespace

const std::string & RuntimeLibrarySource()
{
	static std::string source;
	if (source.empty())
	{
		for (size_t i = 0;
		     i < sizeof(kRuntimeLines) / sizeof(kRuntimeLines[0]); i++)
		{
			source += kRuntimeLines[i];
			source += '\n';
		}
	}
	return source;
}

const char * RuntimeLibraryName()
{
	return "<cppgm++ runtime>";
}

}  // namespace toolchain
